USE suyan_message;
CREATE TABLE `sms_channel` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `channel_code` varchar(32) NOT NULL COMMENT '渠道编码',
  `channel_name` varchar(32) NOT NULL COMMENT '渠道名称',
  `contact_name` varchar(32) NOT NULL COMMENT '联系人',
  `secret_key` varchar(100) NOT NULL COMMENT '安全秘钥key',
  `support_type` varchar(255) NOT NULL COMMENT '支持类型',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_user` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_user_name` varchar(64) DEFAULT NULL COMMENT '创建人名称',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否删除：0.未删除，1.已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_channel_code` (`channel_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信渠道表';
CREATE TABLE `sms_message_record` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';
CREATE TABLE `sms_message_record_0` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';
CREATE TABLE `sms_message_record_1` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';
CREATE TABLE `sms_message_record_2` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';
CREATE TABLE `sms_message_record_3` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';
CREATE TABLE `sms_message_record_4` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';
CREATE TABLE `sms_message_record_5` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';
CREATE TABLE `sms_message_record_6` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';
CREATE TABLE `sms_message_record_7` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';
CREATE TABLE `sms_message_record_8` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';
CREATE TABLE `sms_message_record_9` (
  `id` bigint(20) unsigned NOT NULL COMMENT 'id',
  `batch_code` varchar(64) DEFAULT NULL COMMENT '批次编码',
  `mobile` varchar(20) NOT NULL COMMENT '手机号',
  `channel_id` int(11) NOT NULL COMMENT '渠道id',
  `send_provider` varchar(20) NOT NULL COMMENT '发送供应商',
  `template_code` varchar(32) DEFAULT NULL COMMENT '模版编码',
  `send_type` tinyint(2) unsigned NOT NULL COMMENT '发送类型：1.验证码类 2.营销类',
  `send_status` tinyint(2) unsigned NOT NULL COMMENT '发送状态 0.失败 1.成功 2.未知',
  `send_time` datetime DEFAULT NULL COMMENT '发送时间',
  `content` varchar(255) DEFAULT NULL COMMENT '短信内容',
  `msg_id` varchar(32) DEFAULT NULL COMMENT '返回短信消息ID',
  `msg_result` varchar(255) DEFAULT NULL COMMENT '返回短信错误信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信消息记录表';